all:
	gcc -Iinclude/ src/camera.c src/draw.c src/model.c src/main.c -lSOIL -lopengl32 -lglu32 -lglut32 -lm -o grafika.exe -Wall -Wextra -Wpedantic
linux:
	gcc -Iinclude/ src/camera.c src/draw.c src/model.c src/main.c -lSOIL -lGL -lGLU -lglut -lm -o grafika -Wall -Wextra -Wpedantic

