all:
	gcc -Iinclude/ data/src/camera.c  data/src/draw.c data/src/model.c  data/src/main.c -lSOIL -lopengl32 -lglu32 -lglut32 -lm -o grafika.exe -Wall -Wextra -Wpedantic
linux:
	gcc -Iinclude/ data/src/camera.c  data/src/draw.c data/src/model.c  data/src/main.c -lSOIL -lGL -lGLU -lglut -lm -o grafika -Wall -Wextra -Wpedantic

